name: Kotlin

on:
  push:
    branches: ["main"]
    paths:
      - "codes/kotlin/**/*.kt"
      - "en/codes/kotlin/**/*.kt"
  pull_request:
    branches: ["main"]
    paths:
      - "codes/kotlin/**/*.kt"
      - "en/codes/kotlin/**/*.kt"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        code-dir: ["codes/kotlin", "en/codes/kotlin"]

    name: Kotlin on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Build JAR
        run: kotlinc ${{ matrix.code-dir }}/**/*.kt -include-runtime -d ${{ matrix.code-dir }}/build/test.jar
