name: Rust

on:
  push:
    branches: ["main"]
    paths:
      - "codes/rust/**/*.rs"
      - "codes/rust/Cargo.toml"
      - "en/codes/rust/**/*.rs"
      - "en/codes/rust/Cargo.toml"
  pull_request:
    branches: ["main"]
    paths:
      - "codes/rust/**/*.rs"
      - "codes/rust/Cargo.toml"
      - "en/codes/rust/**/*.rs"
      - "en/codes/rust/Cargo.toml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        code-dir: ["codes/rust", "en/codes/rust"]

    steps:
      - uses: brndnmtthws/rust-action-rustup@v1
        with:
          toolchain: nightly

      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --manifest-path=${{ matrix.code-dir }}/Cargo.toml && cargo build --manifest-path=${{ matrix.code-dir }}/Cargo.toml --release
